### ISSUE TITLE
Documentation site's URL deep linking is broken

### ISSUE THREAD

**Issue by uttrasey** [willowtreeapps/react-reform#16]
You can navigate into a deep link from the root url with no problems.
- Enter url http://willowtreeapps.github.io/react-formable/
- Click to `examples` 
- Browser now shows http://willowtreeapps.github.io/react-formable/examples as expected

The problem is if you refresh the browser or try and deep link directly to that URL you get a 404. Probably a react router issue

**Comment by uttrasey** [comment]
This doesn't seem to be broken when running locally interestingly, might just be an out of date gh-pages, going to try and publish

**Comment by kaw2k** [comment]
Very unintuitively, this is mentioned in #13.

So the problem is push state. Github Pages doesn't support push state so we need to switch react router from that to hash state (or whatever it is called). It is working locally due to the local server supporting push state. 

(I think at least, lol)

**Comment by uttrasey** [comment]
Covered by https://github.com/willowtreeapps/react-formable/issues/13
