### ISSUE TITLE
Validator improvements

### ISSUE THREAD

**Issue by uttrasey** [willowtreeapps/react-reform#18]
- [x] have documentation on the validator API (func args) also a page showing the stock validators once they are written
- [x] ~~provide field context via new argument so a validator can tell which field it's validating (more details below)~~

~~Would be for the validator to be called with an argument allowing it to know the field which is being validated. This will become useful when doing stock validators but needs some thought as to how to handle nesting.~~

^ see comments below, achievable via function currying

**Comment by kaw2k** [comment]
@uttrasey do you have an example of how this could be used? The link in the description is interesting. I was thinking about removing the use of `call` there to help make things more pure. The purer the validators, the better. If we can come up with some solid use cases we could probably accommodate tho.

**Comment by uttrasey** [comment]
Yeh I was thinking of the use case where we have the required field validator which simplistically looks like:

``` js
requiredValidator(value) {
    if (!value)
        return 'Required field missing!';
}
```

If there were multiple required fields (missing) then `<Errors />` ends up looking like:

> Required field missing!
> Required field missing!

Where as it would be nice to pipe in some form of context so you could do:

> First name missing
> Last name missing

Thinking about it maybe we could have a decorator or another prop that would allow you  to pass in a pretty name for the `<Input />`!?

**Comment by kaw2k** [comment]
A simple way to fix this is to have curried validators. Required for example:

``` js
function required(message) {
    return function(value) {
        if(!value || !value.length) return message;
    };
}
```

We can then use the validator as follows:

``` js
<Input name="first" validators={[ required('First error message') ]} />
<Input name="second" validators={[ required('Secodn error message') ]} />
```

Thus far having our validators structured this way has given us a great deal of flexibility.

**Comment by uttrasey** [comment]
:+1:  much simpler I like it
