### ISSUE TITLE
Asynchronous validations

### ISSUE THREAD

**Issue by martinschayna** [willowtreeapps/react-reform#64]
It would be nice to have asynchronous validations i.e. when a server side check is necessary before submitting form. It can be implemented by optional `Promise` return from a validator function.

Maybe, it means some synchronization between already running async validators and/or `onSubmit` event.

Could be possible? What do you think?

**Comment by kaw2k** [comment]
@martinschayna, a solid request. In fact it is already on our radar :smile:

We considered two scenarios:
1. Async validation which happens on a form level
2. Async validation which happens on an input / fieldest / fieldlist level

Form level async validation is simple enough, you can handle it in your `onSubmit` callback. Ideal? Maybe not, but it works for now.

Async validation for components is a much more interesting behaviour. For example, take a look at Twitter's sign up form.

![Twitters sign up form](http://i.imgur.com/bcCkkwM.png)

Without having submitted the form, twitter asynchronously validates the input and displays a warning for the user. How could we do this in our current set up? We could listen to the `onChange` event and run some checks there, but that is too messy. 

If you browse through [this](https://github.com/willowtreeapps/react-formable-inputs/issues/8) issue in [react-formable-inputs](https://github.com/willowtreeapps/react-formable-inputs), we propose another API at the component level. These would be wrappers that can behave as if they were inputs by giving more power to what they contain. If we wanted to emulate Twitter's signup form, it would look something like this.

``` js
function validateTest(value, fieldValues, fieldErrors) {
    return new Promise(function(resolve, reject) {
        return value === 'test' : reject('Bad') : resolve('Good');
    });
}

<Form>
    <AsyncValidationWrapper async={validateTest}>
        <Input name="email" />
    </AsyncValidationWrapper>

    <AsyncValidationWrapper async={validateTest}>
        <Input name="password" type="password" />
    </AsyncValidationWrapper>
</Form>
```

the `async` prop on the `AsyncValidationWrapper` expects a function returning a promise. The result of reject would propagate into the errors of the form. This wrapper could wrap fieldsets or fieldlists as well. 

Anyhow, this is the internal discussion we are having. We have two projects which we are testing it out on. Regardless, this will get some movement soon. 

Thanks for your feedback @martinschayna! Any other thoughts would be appreciate as well :smile:
