### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by janaz** [willowtreeapps/react-reform#67]
Hello,

I have a question about the version mismatch between npm ([0.6.0](https://www.npmjs.com/package/react-formable)) and git ([0.3.0](https://github.com/willowtreeapps/react-formable/releases/tag/v0.3.0))

I was trying to figure out why there's a mismatch and what are the differences between 0.6.0 and 0.3.0?

Cheers

**Comment by kaw2k** [comment]
Hey @janaz,

There was an issue with babel which caused the compiled code to break some of our function compositions. We ended up re-building the code and publishing it to NPM, however it looks like the publish to Github didn't take place. Thanks for pointing this out!
