### ISSUE TITLE
Problems with cloning non inputs

### ISSUE THREAD

**Issue by kaw2k** [willowtreeapps/react-reform#68]
- Any stateless component with a `name` prop gets cloned which throws an error, this is bad as it throws warnings

**Comment by andreipopovici** [comment]
Not only does it throw errors, it prevents using radio button groups within a `react-formable` form.

What's the suggested solution for integrating radio buttons?

**Comment by kaw2k** [comment]
@andreipopovici A simple work around would be to make a simple radio component. We have made a few recently which abstracts away the name property from the inputs.

```
<RadioGroup name="day-radio">
    <label>
        <input type="radio" value="one" />
        <span>Day one</span>
    </label>
    <label>
        <input type="radio" value="nine" />
        <span>One nine</span>
    </label>
</RadioGroup>
```

The `RadioGroup` component clones its children and automatically binds its appropriate props. There are a few components out there that do something similar (ie: https://github.com/chenglou/react-radio-group). You could quite easily write a light wrapper around one of those components which implements `getValue` which would work nicely with formable.

I think ultimately we will either move away from `name` or allow users to specify what property they would like to use. We will see. 

Let me know if that helps!

**Comment by andreipopovici** [comment]
I tried `chenglou`'s radio group and had some unresolved issues, so I went with a hacky workaround for now. Thanks for taking time to reply! :)

**Comment by kaw2k** [comment]
Any time @andreipopovici! Please open issues for any pain points you encounter. I am going through and converting things to typescript and can address things while I'm in the weeds.

**Comment by kaw2k** [comment]
#97 tightens up how we decide if something is formable compatible. Will open up a new ticket for additional inputs to help with the radio problem.
