### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by sanghin** [willowtreeapps/react-reform#75]
Hi and thanks for this package :) . 

As the title suggest he's not working on IE (version 9,10,11) because you are using [Array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) method wich is not implemented on IE for now. 

[I've fixed it in this PR ](https://github.com/willowtreeapps/react-formable/pull/74)

**Comment by killerswan** [comment]
So, it's been a couple months.  Would @kaw2k take a pull req. to stop using those `find` methods?

Seems like there are two of 'em:

```
...>ack -i "\.find\("
lib\helpers\cloneChildren.js
156:                return cloneRules.find(function (rule) {

src\helpers\cloneChildren.js
116:            return cloneRules.find(rule => rule.predicate(child)).clone(child, childNames);
```

**Comment by kaw2k** [comment]
Sorry for the delay, @killerswan PRs are always welcome 😄
