### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by kaw2k** [willowtreeapps/react-reform#77]
Thus far the API to formable has been pretty stable across multiple projects. Time to solidify things 😄. We have encountered a few pain points that I want to address before 1.0, here they are in no particular order.

**Convert the codebase to Typescript**
This will give us several big wins. Access to modern javascript features, tooling support, safeguards to help other contributors enter the project, and types for those who want to use them with formable. 

**Allow for async validation**
We are exploring what API changes would need to happen to permit async validation. This seems to be a critical feature for many people, so having it on an input basis isn't acceptable. 

**Improve how forms interact with lists of data**
Currently we have `Fieldlist` which lets us render lists of forms effortlessly. The other half of the coin is to get that form data back into the list data. This can be done with manually merging the data, but is painful. #9 was the starting point of solving this issue, however may be overly complicated for most users.

Miss anything that sounds critical? Leave your thoughts in the comments!

**Comment by sanghin** [comment]
I'm using typescript and i've made a custom d.ts file it's not a perfect definition file but it allow me to use react-formable with Typescript and it can be a start for you. [Gist here](https://gist.github.com/dbonnay/ae4e2f279854f9e9b33c565c7ab36207).

**Comment by kaw2k** [comment]
Ty @dbonnay! Will certainly look over this 😄 Another benefit of using Typescript will mean auto generated .d.ts files that are always up to date.

**Comment by kaw2k** [comment]
Starting in v2 typings are included 😄
