### ISSUE TITLE
brfs is required for building

### ISSUE THREAD

**Issue by killerswan** [willowtreeapps/react-reform#80]
It seems as though [brfs](https://www.npmjs.com/package/brfs) is required to run `gulp build`, so maybe it should be a dev dependency?

**Comment by kaw2k** [comment]
`brfs` is used within the `react-component-gulp-tasks` (a PR I made into that dependency). We shouldn't be needing it within this repo, however it has been a while since I touched that bit of code. Are you having trouble building from source?

**Comment by killerswan** [comment]
After installing `brfs`, no trouble. :sweat_smile:

**Comment by kaw2k** [comment]
Closing this, in v1 we no longer depend on brfs.
